package IOStreamDemos;

import java.io.FileOutputStream;
import java.sql.Date;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

public class PdfGeneraterDemo {

	public static void main(String[] args)throws Exception {
		Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream("/Users/nija/Desktop/NijaPdfGenerator.pdf"));
        document.open();
        addMetaData(document);
        addTitlePage(document);
       // addContent(document);
        document.close();
	}
	
	private static void addMetaData(Document document) {
        document.addTitle("My first PDF");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Lars Vogel");
        document.addCreator("Lars Vogel");
    }

    private static void addTitlePage(Document document)
            throws DocumentException {
        Paragraph preface = new Paragraph();
        // We add one empty line
        addEmptyLine(preface, 1);
        // Lets write a big header
        preface.add(new Paragraph("Title of the document"));

        addEmptyLine(preface, 1);
        // Will create: Report generated by: _name, _date
        
       

        document.add(preface);
        // Start a new page
        document.newPage();
    }
    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
}}
